### ISSUE TITLE
Suggestion to make this work with stock based marshmallow rom

### ISSUE THREAD

**Issue by hagehoge55** [exynos5420/android_kernel_samsung_exynos5420#4]
Hi, I wanted to use this for stock based roms. 
Then the problem seems to be sdcardfs is old here.
So I experimently replaced fs/sdcardfs with sammy marshmallow kernel source.
Then changed defconfig following ironkernel by tkkg1994 and skyhigh by UpIntheSky

CONFIG_SDCARD_FS=y / already set
CONFIG_SDCARD_FS_FADV_NOACTIVE=y /below was not set
CONFIG_SDCARD_FS_CI_SEARCH=y
CONFIG_SDCARD_FS_XATTR=y

CONFIG_FAT_VIRTUAL_XATTR=y
CONFIG_FAT_VIRTUAL_XATTR_SELINUX_LABEL="u:object_r:sdcard_external:s0"
CONFIG_FAT_SUPPORT_STLOG=y
CONFIG_EXFAT_FS=y
CONFIG_EXFAT_VIRTUAL_XATTR=y
CONFIG_EXFAT_VIRTUAL_XATTR_SELINUX_LABEL="u:object_r:sdcard_external:s0"
CONFIG_EXFAT_SUPPORT_STLOG=y

and added include/linux/fs.h and others for some newly introduced variables guided by the errors from compiler. After this, it seems to work with stock based roms without major problem.

Hope this helps. And thank you for developing and maintaining this kernel.

BTW, I suspect this won't do bad for lineage because it uses FUSE instead of sdcardfs.

**Comment by tincho5588** [comment]
Samsung uses a modified verison of sdcardfs which doesn't work on lineage, or any AOSP rom...
We replaced samsung's sdcardfs with the AOSP version to make it compatible... so no, we can't replace the current implementation... this issue is basically asking to roll back all the changes we did to have sdcardfs on AOSP based roms...
